### ISSUE TITLE
Use IPC communication instead of TCP

### ISSUE THREAD

**Issue by omichel** [cyberbotics/competition-record-action#17]
The current implementation uses TCP/IP to communicate between the controller container and the Webots container.
However, Webots also supports using IPC to communicate across containers through a shared volume containing shared memory segments and pipes. Such a solution is faster than using TCP, especially for camera and lidar images. Therefore, we should use this approach instead of TCP/IP.

**Comment by Jean-Eudes-le-retour** [comment]
For the memory segments we might need https://docs.docker.com/engine/reference/run/#ipc-settings---ipc

For the pipes, I tested running Webots locally and running an external controller in a container adding `-v /tmp/webots-1234/ipc:/tmp/webots-1234/ipc` to `docker run` ([source](https://stackoverflow.com/questions/44029035/ipc-communication-between-docker-containers)) and it's able to connect to Webots

**Comment by omichel** [comment]
I believe we do not need the ipc stuff from Docker as the memory segments are simply memory mapped files, so mounting the volume should be sufficient.
